[package]
name = "dao-certificate-check-lock"
version = "0.1.0"
edition = "2021"

[dependencies]
ckb-std = "0.15.3"

ckb-cinnabar-verifier = { workspace = true }

[features]
default = ["mainnet"]
mainnet = []
testnet = []
unitest = []
